README.md
src/index.js

Minor docs updates / fixes.
* added a few examples to readme
* correct docs link for ACS API to "Triggering a Signal activity"

add examples in readme, correct ACS docs link

---

package.json
src/helpers.js
src/index.js
test/index.test.js

Usage of cross-fetch, debug logging of cross-fetch request/response

---

README.md
package.json
src/helpers.js
src/index.js

Usage of @adobe/aio-lib-core-logging library
Common logging library usage.
Manual tests.

ACNA-432 - Integrate Adobe Campaign Standard API Wrapper with CNA logging

---

e2e/e2e.js
package.json

Basic e2e tests (read only API)
Diagnostics for connecting to the server.
npm run e2e with a `e2e/.env` file with the appropriate credentials

Add e2e tests

---

README.md
e2e/e2e.js
src/index.js
test/index.test.js

e2e tests for custom resources
npm test
npm run e2e

Add e2e for custom resources

---

jest/jest.fixture.setup.js
jest/jest.fs.setup.js
jest/jest.swagger.setup.js
jest/mocks/swagger-client.js

Move manual mocks to root jest folder
Fix eslint globals issue
Prep for template
npm test
npm run e2e

Jest mock restructure

---

jest/mocks/swagger-client.js

Remove api-specific mock code.
Prep for template
npm test
npm run e2e

Remove api-specific code in swagger-client mock

---

e2e/e2e.js

Closes #49 
Consistent e2e tests, not dependent on server inconsistencies
npm run e2e
npm test

fix: Fix e2e test getAllProfiles (bad tenant id)

---

package.json
src/index.js
test/.eslintrc
test/index.test.js
test/jest/jest.fetch.setup.js

chore(package): update jest-fetch-mock to version 3.0.1

---

e2e/e2e.js
src/index.js
test/index.test.js

fix: ACNA-612 - createProfile method fails with 404 - Not Found

---

package.json

fix: pin swagger-client@3.10.1

---

package.json

chore(package): update eslint-plugin-jest to version 23.10.0

---

README.md
docs/readme_template.md
src/index.js

fix: ACNA-696 - campaignStandardCoreAPI.sendTransactionalEvent does not identify event to trigger

---

README.md
src/index.js

fix: ACNA-899 - campaignStandardCoreAPI.getTransactionalEvent should accept an extra macTenantId parameter

---

README.md

Update Campaign URL in README.

update campaign url

---

e2e/e2e.js

fix: e2e test failures under node 10

---

src/index.js
test/index.test.js

fix: triggerSignalActivity() throws error when workflow is called during it's "cooldown"

---

README.md
src/index.js

Updated doc for getMatadataForResourceExt to match its return data.
Fixes #84

Update documentation of getMetadataForResourceExt 

---

.github/dependabot.yml

Adding dependabot to the repo.
[ACNA-1969](https://jira.corp.adobe.com/browse/ACNA-1969)

dependabot added

---

package.json
test/jest/mocks/swagger-client.js

chore(dev-deps): update jest to v29
